# Generated by Django 5.0 on 2024-01-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_usersdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersdata',
            options={'managed': True},
        ),
    ]
